./contours -f ../inputs/trig.txt -n 1 -b 32
./contours -f ../inputs/trig.txt -n 1 -b 32
./contours -f ../inputs/trig.txt -n 1 -b 32
./contours -f ../inputs/trig.txt -n 2 -b 32
./contours -f ../inputs/trig.txt -n 2 -b 32
./contours -f ../inputs/trig.txt -n 2 -b 32
./contours -f ../inputs/trig.txt -n 4 -b 32
./contours -f ../inputs/trig.txt -n 4 -b 32
./contours -f ../inputs/trig.txt -n 4 -b 32
./contours -f ../inputs/trig.txt -n 8 -b 32
./contours -f ../inputs/trig.txt -n 8 -b 32
./contours -f ../inputs/trig.txt -n 8 -b 32
./contours -f ../inputs/trig.txt -n 16 -b 32
./contours -f ../inputs/trig.txt -n 16 -b 32
./contours -f ../inputs/trig.txt -n 16 -b 32
./contours -f ../inputs/trig.txt -n 32 -b 32
./contours -f ../inputs/trig.txt -n 32 -b 32
./contours -f ../inputs/trig.txt -n 32 -b 32
